### PR TITLE
replace <? with <?php

### PR DESCRIPTION
**Pull request by Tjoosten**

### CODE REVIEW

**Comment by stevenrombauts** [comment]
Hi @Tjoosten! You're the very first contributor to the intranet repository! That earns you a spot in the Timble hall of fame! Thank you very much.

However, there's no need to replace the short tags with <?php tags. The _short echo tag_ has been a standard of PHP since 5.4. Have a look at [this PHP RFC entry](https://wiki.php.net/rfc/shortags) for some more background. 

You will also notice that the  _short open tags_ are only found in template files (eg. files inside a `tmpl` folder). That's because we add some of our own magic to them and replace the tags so they can be parsed by PHP. This shorthand notation makes the templates easier to read and work with.

Nevertheless, we value your contribution greatly. Thanks for taking the time to improve the project.

We noticed you're from Belgium too! We've set up camp in [Diest](http://www.timble.net/contact/).  If you want to come over for some PHP chatter over a cup of coffee some day, you're most welcome!

**Comment by johanjanssens** [comment]
Oh and feel free to replace [coffee] with one or more other liquid substance(s) of your choosing ... :)

**Comment by Tjoosten** [comment]
What u think of Thursday? And where i find that hall of fame?

**Comment by johanjanssens** [comment]
Hi Tim, Thursday works great, somewhere in the afternoon ? Our office is 5 min walk from the train station. To stay in touch, feel free to email us at info@timble.net

**Comment by Tjoosten** [comment]
Need to come from Turnhout. What hour u want? I don't bother u guys.

**Comment by johanjanssens** [comment]
Lets make it 2pm ?

**Pull request closed without merging**
